# Generated by Django 5.2.5 on 2025-08-22 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('url_imagen', models.TextField(blank=True, null=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sede')),
            ],
            options={
                'unique_together': {('codigo', 'sede')},
            },
        ),
    ]
